### ISSUE TITLE
Feature Request : Pysolar for Solar Trackers

### ISSUE THREAD

**Issue by happytm** [enesbcs/rpieasy#79] opened 2019-07-19 06:55 UTC
Hi ,

This is the library to calculate Sun position at precise time for particular location based on long/lat input from user. I believe in RPIEasy all these input data are collected already. If implemented as a plugin this could be very useful in many application including Solar Trackers, Heliostats etc.You also already implemented 28BYJ-48 Stepper Motor plugin.With sun position data,stepper motors & help of some rules it will be very easy & inexpensive to make a 2 axis solar tracker. Following is link to library & some other links:

https://pysolar.readthedocs.io/en/latest/#

Arduino code & detailed explanation of the code:

https://www.instesre.org/ArduinoUnoSolarCalculations.pdf

Thanks

**Comment by enesbcs** [comment] 2019-07-19 17:43
Interesting idea... i guess it may be used as a global variable like %azimuth% and %altitude%?

**Comment by happytm** [comment] 2019-07-19 20:02
Yes that will be nice. Also they have "get_radiation_direct" to get solar radiation in watts.It is not necessary for tracker but it is extra data point to study future efficiency of solar panel before installation for particular area.

Thanks

**Comment by enesbcs** [comment] 2019-07-22 16:28
Feature added in commit https://github.com/enesbcs/rpieasy/commit/2ce294749d49bb8e71544cfd51e0dabf547fc173

Pysolar can be installed at Tools->Advanced settings, %sun_altitude%, %sun_azimuth%, %sun_radiation% are now available.

- Are there decimals needed and if yes, how many?
- For stepper motor usage with solar panels, how can be handled the negative Altitude? Are there other variables or functions needed for use? Or the stepper motor needs some kind of user changeable limits?

**Comment by happytm** [comment] 2019-07-23 20:07
First of all thank you for adding this feature to RPIEasy.I appreciate it.I clearly did not expect you to do it so fast. So to answer your questions I will have to setup solar hardware with pan tilt mechanism first to check accuracy of sun position provided by PySolar. I will have to play with some rules to test accuracy of sun tracker. I think functions and variables are ok for solar tracker purpose.I think altitude never will be in negative according to their documentation below;

> The reference frame for Pysolar is shown in the figure below. Altitude is reckoned with zero at the horizon. The altitude is positive when the sun is above the horizon. Azimuth is reckoned with zero corresponding to north. Positive azimuth estimates correspond to estimates east of north; negative estimates, or estimates larger than 180 are west of north. In the northern hemisphere, if we speak in terms of (altitude, azimuth), the sun comes up around (0, 90), reaches (70, 180) around noon, and sets around (0, 270).

Thanks again.

**Comment by happytm** [comment] 2019-07-25 20:20
Trying to write some simple rules for sun tracker but I am stuck at first rule which is below (dummy sensor is at task#12):

on Clock#Time do
if %syshour% > 5 and %syshour% < 20
TaskValueSet,12,1,%sun_azimuth%
TaskValueSet,12,2,%sun_altitude%
endif
endon

I do not see values stored in dummy device.Are the rules above right or I am something wrong here?
I am using latest firmware from yesterday.

Please help.
Thanks

**Comment by enesbcs** [comment] 2019-07-25 21:28
Did you install pysolar from RPIEasy->Tools->Advanced?
What did you see in Tools->System Variables? And in console debug log in the meantime?

**Comment by enesbcs** [comment] 2019-07-25 21:30
By the way the altitude can be negative, currently it is night and i get these at System Variables:

%sunset% | 20:16
-- | --
%sun_altitude% | -21.6735174881
%sun_azimuth% | 341.147858449
%sun_radiation% | 0.0

**Comment by happytm** [comment] 2019-07-25 22:19
Pysolar is working fine and I think giving data according to my location in system variables.I am trying to avoid negative values in night time by using Clock#Time event in rules as you can see in the rule I posted.I want to store %sun_altitude% and %sun_azimuth% values in the dummy device with 0 decimal so I can use it in above ruleset.The problem is rule is not storing this values to dummy device and console log do not show this event triggered.I think I am doing something wrong in above rule.

Thanks

**Comment by enesbcs** [comment] 2019-07-26 05:34
There are other problems in rules which is now fixed https://github.com/enesbcs/rpieasy/commit/2bf1469d21b0b50b2426306f1a4918b670fc81c9

Yes the pins from 31 through 40 will be totally OK if you do not plan to use SPI1.

The following rule is working to me:
```
on Clock#Time=All,**:** do
 if %syshour% > 5 and %syshour% < 20
  TaskValueSet,12,1,%sun_azimuth%
  TaskValueSet,12,2,%sun_altitude%
 endif
endon
```

**Comment by happytm** [comment] 2019-07-26 18:47
Thank you. Your example rule worked fine and now I can store azimuth & altitude values in dummy device. 
I have another problem now. In stepper plugin for some reason I can not save pin no for 4th GPIO.

Can you please try creating stepper plugin and set all 4 GPIO pin ? 

Thanks

**Comment by enesbcs** [comment] 2019-07-26 19:13
I see. It looks like that webserver.py suffered from a little regression bug. :( Fixed at commit https://github.com/enesbcs/rpieasy/commit/561b8dfa45500727f0d4d653601f8ded1be151a4

**Comment by happytm** [comment] 2019-07-26 20:32
Now it works. I have pan/tilt setup and now observing power consumption.With following rules it uses upto 700ma on raspberry pi zero W when both motors are active but otherwise it is tracking sun nicely:

on Clock#Time=All,**:** do
 if %syshour% > 5 and %syshour% < 20
  TaskValueSet,12,1,%sun_azimuth%
  TaskValueSet,12,2,%sun_altitude%
  motor,azimuth,pos,[sun#azimuth]
  motor,altitude,pos,[sun#altitude]
 endif
endon

Thanks again for quick fix.

**Comment by enesbcs** [comment] 2019-07-27 14:34
Ok thank you for feedback, stepper issue reopened at https://github.com/enesbcs/rpieasy/issues/58

**Closed by enesbcs** 2019-07-27 14:34 UTC
Labels: Core related, awaiting for feedback, enhancement
